// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Categoria documents
 */
interface CategoriaDocumentData {
  /**
   * nome field in *Categoria*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categoria.nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;
}

/**
 * Categoria document from Prismic
 *
 * - **API ID**: `categoria`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoriaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoriaDocumentData>,
    "categoria",
    Lang
  >;

/**
 * Content for Estabelecimentos documents
 */
interface EstabelecimentosDocumentData {
  /**
   * nome field in *Estabelecimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: estabelecimentos.nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * categoria field in *Estabelecimentos*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: estabelecimentos.categoria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  categoria: prismic.ContentRelationshipField<"categoria">;

  /**
   * Tipo field in *Estabelecimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: estabelecimentos.tipo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tipo: prismic.KeyTextField;

  /**
   * telefone field in *Estabelecimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: estabelecimentos.telefone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telefone: prismic.KeyTextField;

  /**
   * instagram field in *Estabelecimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: estabelecimentos.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram: prismic.KeyTextField;
}

/**
 * Estabelecimentos document from Prismic
 *
 * - **API ID**: `estabelecimentos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EstabelecimentosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EstabelecimentosDocumentData>,
    "estabelecimentos",
    Lang
  >;

export type AllDocumentTypes = CategoriaDocument | EstabelecimentosDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CategoriaDocument,
      CategoriaDocumentData,
      EstabelecimentosDocument,
      EstabelecimentosDocumentData,
      AllDocumentTypes,
    };
  }
}
