// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Aprender documents
 */
interface AprenderDocumentData {
  /**
   * Título field in *Aprender*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aprender.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descrição field in *Aprender*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aprender.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;
}

/**
 * Aprender document from Prismic
 *
 * - **API ID**: `aprender`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AprenderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AprenderDocumentData>,
    "aprender",
    Lang
  >;

/**
 * Content for Categoria documents
 */
interface CategoriaDocumentData {
  /**
   * nome field in *Categoria*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categoria.nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;
}

/**
 * Categoria document from Prismic
 *
 * - **API ID**: `categoria`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoriaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoriaDocumentData>,
    "categoria",
    Lang
  >;

/**
 * Content for Como chegar documents
 */
interface ComoChegarDocumentData {
  /**
   * Título field in *Como chegar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_chegar.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descrição field in *Como chegar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_chegar.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;
}

/**
 * Como chegar document from Prismic
 *
 * - **API ID**: `como_chegar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ComoChegarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ComoChegarDocumentData>,
    "como_chegar",
    Lang
  >;

/**
 * Content for Contato documents
 */
interface ContatoDocumentData {
  /**
   * Título field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descrição field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;
}

/**
 * Contato document from Prismic
 *
 * - **API ID**: `contato`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContatoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContatoDocumentData>,
    "contato",
    Lang
  >;

/**
 * Content for Doações documents
 */
interface DoacoesDocumentData {
  /**
   * Título field in *Doações*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: doacoes.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descrição field in *Doações*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: doacoes.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;
}

/**
 * Doações document from Prismic
 *
 * - **API ID**: `doacoes`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DoacoesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DoacoesDocumentData>,
    "doacoes",
    Lang
  >;

/**
 * Content for Estabelecimentos documents
 */
interface EstabelecimentosDocumentData {
  /**
   * nome field in *Estabelecimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: estabelecimentos.nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * categoria field in *Estabelecimentos*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: estabelecimentos.categoria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  categoria: prismic.ContentRelationshipField<"categoria">;

  /**
   * Tipo field in *Estabelecimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: estabelecimentos.tipo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tipo: prismic.KeyTextField;

  /**
   * telefone field in *Estabelecimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: estabelecimentos.telefone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telefone: prismic.KeyTextField;

  /**
   * instagram field in *Estabelecimentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: estabelecimentos.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram: prismic.KeyTextField;
}

/**
 * Estabelecimentos document from Prismic
 *
 * - **API ID**: `estabelecimentos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EstabelecimentosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EstabelecimentosDocumentData>,
    "estabelecimentos",
    Lang
  >;

/**
 * Content for EventoHome documents
 */
interface EventohomeDocumentData {
  /**
   * Título field in *EventoHome*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: eventohome.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * imagem field in *EventoHome*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eventohome.imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * link field in *EventoHome*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: eventohome.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * EventoHome document from Prismic
 *
 * - **API ID**: `eventohome`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventohomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EventohomeDocumentData>,
    "eventohome",
    Lang
  >;

/**
 * Content for Eventos documents
 */
interface EventosDocumentData {
  /**
   * Data field in *Eventos*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.data
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  data: prismic.DateField;

  /**
   * Título field in *Eventos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Resumo field in *Eventos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.resumo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  resumo: prismic.RichTextField;

  /**
   * Imagem field in *Eventos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * Descrição field in *Eventos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;

  /**
   * ordem field in *Eventos*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.ordem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ordem: prismic.NumberField;
}

/**
 * Eventos document from Prismic
 *
 * - **API ID**: `eventos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EventosDocumentData>,
    "eventos",
    Lang
  >;

/**
 * Content for Hotelaria documents
 */
interface HotelariaDocumentData {
  /**
   * Título field in *Hotelaria*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hotelaria.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Imagem field in *Hotelaria*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hotelaria.imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * Descrição field in *Hotelaria*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hotelaria.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;
}

/**
 * Hotelaria document from Prismic
 *
 * - **API ID**: `hotelaria`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HotelariaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HotelariaDocumentData>,
    "hotelaria",
    Lang
  >;

/**
 * Content for Pontos turísticos documents
 */
interface PontosTuristicosDocumentData {
  /**
   * Título field in *Pontos turísticos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pontos_turisticos.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * imagem field in *Pontos turísticos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pontos_turisticos.imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * Descrição field in *Pontos turísticos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pontos_turisticos.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;

  /**
   * ordem field in *Pontos turísticos*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: pontos_turisticos.ordem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  ordem: prismic.NumberField;
}

/**
 * Pontos turísticos document from Prismic
 *
 * - **API ID**: `pontos_turisticos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PontosTuristicosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PontosTuristicosDocumentData>,
    "pontos_turisticos",
    Lang
  >;

export type AllDocumentTypes =
  | AprenderDocument
  | CategoriaDocument
  | ComoChegarDocument
  | ContatoDocument
  | DoacoesDocument
  | EstabelecimentosDocument
  | EventohomeDocument
  | EventosDocument
  | HotelariaDocument
  | PontosTuristicosDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AprenderDocument,
      AprenderDocumentData,
      CategoriaDocument,
      CategoriaDocumentData,
      ComoChegarDocument,
      ComoChegarDocumentData,
      ContatoDocument,
      ContatoDocumentData,
      DoacoesDocument,
      DoacoesDocumentData,
      EstabelecimentosDocument,
      EstabelecimentosDocumentData,
      EventohomeDocument,
      EventohomeDocumentData,
      EventosDocument,
      EventosDocumentData,
      HotelariaDocument,
      HotelariaDocumentData,
      PontosTuristicosDocument,
      PontosTuristicosDocumentData,
      AllDocumentTypes,
    };
  }
}
